services:
- type: web
  name: line-bot-eat_what
  env: python
  repo: https://github.com/paulchi-intel/line-bot-sdk-python/compare/master...paulchi-intel-patch-1.git
  buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
  startCommand: cd examples/flask-echo;gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: 259KhHhK9JkcNBApp5AN49wK2f4mjHOSonztVEOlZ4qExdCwZrEhXJxvYjiee0T+adOuVDseVzZesGdKSopsxraMRjmY47XLaX0booeyplmG7WHgJ4zr8PE0/72Bq5GLWim3Nop+yAMKPAWVVO2IYgdB04t89/1O/w1cDnyilFU=
    sync: false
  - key: ccd99ccd0896fd6354b57eec2dad677f
    sync: false
# - type: web
#   name: line-bot-python-flask-with-handler
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-echo;gunicorn app_with_handler:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-flask-kitchensink
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-kitchensink;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-kitchensink;gunicorn app:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-simple-server
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/simple-server-echo;pip install -r requirements.txt
#   startCommand: cd examples/simple-server-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-aiohttp
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/aiohttp-echo;pip install -r requirements.txt
#   startCommand: cd examples/aiohttp-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
